listen_addresses = '*'
hba_file = '/etc/postgresql/pg_hba.conf'
password_encryption = 'scram-sha-256'

wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = '256MB'

hot_standby = on
wal_receiver_status_interval = '1s'

max_connections = 100
shared_buffers = '128MB'

logging_collector = off
log_line_prefix = '%m [%p] '